# Generated by Django 3.2.9 on 2021-11-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('user_pw', models.CharField(max_length=200)),
            ],
        ),
    ]
