# Generated by Django 3.2.9 on 2021-12-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FosterComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FosterPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('contents', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
