# Generated by Django 3.2.9 on 2021-12-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_fostercomment_fosterpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='fostercomment',
            name='user_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='fosterpost',
            name='user_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='user_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='fosterpost',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
