# Generated by Django 3.2.9 on 2021-12-11 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_remove_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(db_column='post_id', default='', on_delete=django.db.models.deletion.CASCADE, to='community.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(help_text='Comment ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(help_text='Post ID', primary_key=True, serialize=False),
        ),
    ]
